### ISSUE TITLE
IoT Analytics todo items: General changes

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#233]
This is a list of general purpose changes on UI to make Countly collect data from IoT devices. Note that IoT Analytics is in beta and is not meant for public consumption.

- [x] By default, remove Populate data plugin until relevant data is populated. 
- [x] Drill will show "View Device List" button instead of "View User List"
- [x] Remove device loyalty plugin
- [x] Remove "Returning Devices" under Analytics -> Devices
- [x] Remove Top resolution from Analytics > Device Types
- [x] Remove Languages plugin by default as it may not be relevant.
- [x] When IoT Application Type is selected, Category & Demo Data is removed.
- [x] Remove "Engagement > Device retention"
- [x] Remove Funnels.
- [x] Remove unrelated drop down elements in Drill.
- [x] Remove Flows plugin.
