### ISSUE TITLE
IoT Analytics todo items: session related changes

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#234]
This is a task list related to session related modifications.  Note that IoT Analytics is in beta and is not meant for public consumption.

- [x] Remove or disable Analytics > Sessions plugin/view
- [x] Remove "Total sessions" from Analytics > Countries. 
- [x] Remove "Sessions button" inside maps in Analytics > Countries. Only total devices and new devices will be left.
- [x] Remove "Total Sessions" from Analytics > Versions
- [x] Remove "Total Sessions" from Analytics > Platforms
- [x] Remove "Total Sessions", "Time Spent", "Avg Time Spent" from All Apps
- [x] Remove everything under Engagement.
