### ISSUE TITLE
IoT Analytics todo items: device list table and device profile changes

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-server#235]
This is a list of device list table and device profile changes. Note that IoT Analytics is in beta and is not meant for public consumption.
- [x] "Name" should be renamed to "Device Name"
- [ ] Device Name should be able to be modified by hand
- [x] Remove "Total Sessions"
- [x] Remove "Total Time Spent"
- [ ] Add "This device is connected" to this page
- [x] Remove "Engagement" color chart
- [ ] Use device icon instead of head icon (gravatar)
- [ ] Remove username, email, organization, full-name (because it's already defined at top), carrier, contact-phone, gender, age
- [ ] Add Number of sensors connected (e.g "Sensors: 4")
- [x] Use "First communication" instead of "First seen". Beautiful time can be used (e.g a "few seconds ago").
- [x] Use "Last communication" instead of "Last seen". Beautiful time can be used.
- [x] Use "Last communication" instead of "Last seen". Beautiful time can be used.
- [x] Hide "Total sessions"
- [x] Remove everything related to purchase
- [ ] Remove "Notes" section
- [ ] Remove "Timeline" chart
- [ ] Remove "Session History"
- [ ] Remove "Funnel Progress"
